<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 30.03.2018
 * Time: 14:40
 */

namespace App\Services;


use App\Repositories\BannerRepository;
use App\Repositories\CategoryRepository;
use App\Repositories\MainSliderRepository;
use App\Repositories\ProductRepository;

class HomeService extends LayoutService
{
    protected $main_slider_repository;

    protected $product_repository;

    protected $banner_repository;

    public function __construct(CategoryRepository $categoryRepository,
                                MainSliderRepository $mainSliderRepository,
                                ProductRepository $productRepository,
                                BannerRepository $bannerRepository)
    {
        parent::__construct($categoryRepository);

        $this->main_slider_repository = $mainSliderRepository;

        $this->product_repository = $productRepository;

        $this->banner_repository = $bannerRepository;
    }

    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fill_main_slider($model);

        $this->fill_new_slider_products($model);

        $this->fill_banners($model);
    }

    private function fill_main_slider($model)
    {
        $model->main_slider = $this->main_slider_repository->get_main_slider($model);
    }

    private function fill_new_slider_products($model)
    {
        $model->new_slider_products = $this->product_repository->get_new_slider_products($model);
    }

    private function fill_banners($model)
    {
        $model->banners = $this->banner_repository->get_banners($model);
    }
}