<?php


namespace App\Services;

use App\Repositories\CategoryRepository;
use App\Repositories\MetaTagRepository;
use App\Repositories\OrderRepository;

class OrderPaymentService extends LayoutService
{
    protected $metaTagRepository;

    protected $orderRepository;

    public function __construct(CategoryRepository $categoryRepository,
                                MetaTagRepository $metaTagRepository,
                                OrderRepository $orderRepository)
    {
        parent::__construct($categoryRepository);

        $this->orderRepository = $orderRepository;

        $this->metaTagRepository = $metaTagRepository;
    }

    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillOrderStatuses($model);

        $this->fillOrder($model);

        $this->fillStatus($model);

        $this->fillMetaTags($model);

        $this->initLiqpay($model);
    }

    public function fillOrderStatuses($model)
    {
        $model->orderStatuses = $this->orderRepository->getOrderStatuses($model);
    }

    public function fillOrder($model)
    {
        $model->order = $this->orderRepository->getOrder($model);

        if (is_null($model->order))
        {
            abort(404);
        }
    }

    public function fillStatus($model)
    {
        foreach ($model->orderStatuses as $orderStatus)
        {
            if ($model->order->status_id == $orderStatus->id)
            {
                $model->status = $orderStatus;
            }
        }
    }

    /**
     * @param $model
     */
    private function fillMetaTags($model)
    {
        $metaTag = $this->metaTagRepository->getMetaTagByPageName($model);
        $model->title = $metaTag->title;
        $model->description = $metaTag->description;
        $model->keywords = $metaTag->keywords;
        $model->h1 = $metaTag->h1;
    }
}