<?php

namespace App\Services;


use App\Repositories\CategoryRepository;

class StaticPaymentDeliveryService extends LayoutService
{
    public function __construct(CategoryRepository $categoryRepository)
    {
        parent::__construct($categoryRepository);
    }

    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillMetaTags($model);
    }

    private function fillMetaTags($model)
    {
        $model->title = trans('header.payment_delivery');
        $model->description = trans('header.payment_delivery');
        $model->keywords = trans('header.payment_delivery');
        $model->h1 = trans('header.payment_delivery');
    }
}